<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>Appointment.Booking</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Appointment.Booking.Domain\Appointment.Booking.Domain.csproj" />
    <ProjectReference Include="..\Appointment.Booking.TestBase\Appointment.Booking.TestBase.csproj" />
  </ItemGroup>

</Project>
